services:
  turtl_bio:
    build:
      context: ./turtl.bio
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./turtl.bio/.env
    environment:
      - BACKEND_URL=http://turtl_bio_backend:8080

  turtl_bio_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./:/code
    env_file:
      - ./backend/.env
